# Generated by Django 4.2.2 on 2023-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Movies/img')),
            ],
        ),
    ]
